version: '3'
services:
    central:
        image: slave
        container_name: central
        hostname: central

    slave-zebra:
        image: slave
        container_name: zebra
        hostname: zebra

    slave-giraffe:
        image: slave
        container_name: giraffe
        hostname: giraffe

    slave-elephant:
        image: slave
        container_name: elephant
        hostname: elephant

    dns:
        image: defreitas/dns-proxy-server
        container_name: dns-proxy-server
        hostname: dns.mageddo
        restart: unless-stopped
        ports: 
            - "5380:5380"
        volumes:
            - "/opt/dns-proxy-server/conf:/app/conf"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/run:/host/run"
        environment:
            - MG_RESOLVCONF=/host/run/resolvconf/resolv.conf


